/* Window Works Team Portal - training module viewer and quiz engine.
   Loaded by the sales trainee pages. Depends on api() and cols() from the page.

   Content comes from modules.json at the repo root, generated by build.py in the
   training repo. It is fetched with a timestamp so a content upload goes live
   without touching any HTML.

   Answer keys arrive encoded rather than in the clear. That stops a trainee
   reading them out of view-source. It is deliberately not real security: the
   file is public either way, and the live mock measure is the actual gate.

   Call from the page:  initTraining('Tyler Wallace', 'sales-b2c');
*/
(function () {
  'use strict';

  var MODULES_URL = 'modules.json';
  var TAB_DONE = 'Training_Completions';
  var TAB_RESP = 'Training_Quiz_Responses';
  var KEY = 'windowworks';

  var S = {
    employee: '',
    role: '',
    modules: [],
    done: {},
    current: null,
    busy: false
  };

  /* ---------- small helpers ---------- */

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function el(id) { return document.getElementById(id); }

  function todayStr() { return new Date().toLocaleDateString('en-US'); }

  function decKey(s) {
    try {
      var bin = atob(s);
      var bytes = new Uint8Array(bin.length);
      for (var i = 0; i < bin.length; i++) {
        bytes[i] = bin.charCodeAt(i) ^ KEY.charCodeAt(i % KEY.length);
      }
      return JSON.parse(new TextDecoder().decode(bytes));
    } catch (e) { return null; }
  }

  /* Build a sheet row positionally only after resolving every column by header
     name through cols(). Never index a sheet column by hand. */
  function buildRow(width, c, pairs) {
    var row = [];
    for (var i = 0; i < width; i++) row.push('');
    pairs.forEach(function (p) {
      var ix = c(p[0]);
      if (ix >= 0) row[ix] = p[1];
    });
    return row;
  }

  function sameSet(a, b) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) return false;
    var x = a.slice().sort(), y = b.slice().sort();
    for (var i = 0; i < x.length; i++) { if (x[i] !== y[i]) return false; }
    return true;
  }

  /* ---------- markdown ---------- */

  function inlineMd(t) {
    t = esc(t);
    t = t.replace(/`([^`]+)`/g, '<code class="tr-code">$1</code>');
    t = t.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    return t;
  }

  function mdTable(rows) {
    var cells = rows.map(function (r) {
      return r.replace(/^\|/, '').replace(/\|$/, '').split('|').map(function (c) { return c.trim(); });
    });
    var head = cells[0] || [];
    var body = cells.slice(1).filter(function (r) { return !/^[-: ]*$/.test(r.join('')); });
    var h = '<thead><tr>' + head.map(function (c) { return '<th>' + inlineMd(c) + '</th>'; }).join('') + '</tr></thead>';
    var b = '<tbody>' + body.map(function (r) {
      return '<tr>' + r.map(function (c) { return '<td>' + inlineMd(c) + '</td>'; }).join('') + '</tr>';
    }).join('') + '</tbody>';
    return '<div class="table-wrap"><table class="data-table">' + h + b + '</table></div>';
  }

  function isBlockStart(t) {
    return !t || /^#{1,6}\s/.test(t) || t.charAt(0) === '|' || /^>\s?/.test(t) ||
      /^[-*]\s+/.test(t) || /^\d+\.\s+/.test(t);
  }

  /* Collect a list, folding wrapped continuation lines into the item above.
     The source is hard-wrapped, so an item can run across several lines and
     bold markers can open on one line and close on the next. */
  function takeList(lines, i, marker, tag, out) {
    var items = [];
    while (i < lines.length) {
      var t = lines[i].trim();
      if (marker.test(t)) {
        items.push(t.replace(marker, ''));
        i++;
      } else if (items.length && t && !isBlockStart(t)) {
        items[items.length - 1] += ' ' + t;
        i++;
      } else {
        break;
      }
    }
    out.push('<' + tag + ' class="tr-' + tag + '">' +
      items.map(function (x) { return '<li>' + inlineMd(x) + '</li>'; }).join('') +
      '</' + tag + '>');
    return i;
  }

  function md(src) {
    var lines = String(src || '').replace(/\r/g, '').split('\n');
    var out = [], i = 0;
    while (i < lines.length) {
      var t = lines[i].trim();
      if (!t) { i++; continue; }

      var h = t.match(/^(#{1,6})\s+(.*)$/);
      if (h) {
        var lv = Math.min(h[1].length + 1, 6);
        out.push('<h' + lv + ' class="tr-h">' + inlineMd(h[2]) + '</h' + lv + '>');
        i++; continue;
      }
      if (t.charAt(0) === '|') {
        var tbl = [];
        while (i < lines.length && lines[i].trim().charAt(0) === '|') { tbl.push(lines[i].trim()); i++; }
        out.push(mdTable(tbl)); continue;
      }
      if (/^>\s?/.test(t)) {
        var bq = [];
        while (i < lines.length && /^>\s?/.test(lines[i].trim())) {
          bq.push(lines[i].trim().replace(/^>\s?/, '')); i++;
        }
        out.push('<blockquote class="tr-bq">' + inlineMd(bq.join(' ')) + '</blockquote>'); continue;
      }
      if (/^[-*]\s+/.test(t)) { i = takeList(lines, i, /^[-*]\s+/, 'ul', out); continue; }
      if (/^\d+\.\s+/.test(t)) { i = takeList(lines, i, /^\d+\.\s+/, 'ol', out); continue; }
      var para = [];
      while (i < lines.length && !isBlockStart(lines[i].trim())) { para.push(lines[i].trim()); i++; }
      out.push('<p class="tr-p">' + inlineMd(para.join(' ')) + '</p>');
    }
    return out.join('');
  }

  /* ---------- video ---------- */

  function videoBlock(m) {
    var v = (m.video || '').trim();
    if (!v || v === 'none') return '';
    var lm = v.match(/loom\.com\/share\/([A-Za-z0-9]+)/);
    if (lm) {
      return '<div class="tr-video"><iframe src="https://www.loom.com/embed/' + esc(lm[1]) +
        '" frameborder="0" allowfullscreen></iframe></div>';
    }
    return '<p class="tr-p"><a class="doc-link" href="' + esc(v) + '" target="_blank" rel="noopener">Open the video</a></p>';
  }

  /* ---------- data ---------- */

  function pathModules() {
    return S.modules.filter(function (m) {
      return (m.roles || []).indexOf(S.role) >= 0;
    });
  }

  function quizTotal(m) {
    return (m.quiz || []).reduce(function (a, q) { return a + (Number(q.points) || 0); }, 0);
  }

  async function loadModules() {
    var res = await fetch(MODULES_URL + '?t=' + Date.now());
    if (!res.ok) throw new Error('modules.json ' + res.status);
    var d = await res.json();
    S.modules = (d && d.modules) || [];
  }

  async function loadCompletions() {
    S.done = {};
    var d = await api({ action: 'read', tab: TAB_DONE });
    if (!d || !d.success || !d.data || !d.data.length) return;
    var c = cols(d.data[0]);
    d.data.slice(1).forEach(function (r) {
      if ((r[c('Employee')] || '').toString().trim() !== S.employee) return;
      var id = (r[c('Module ID')] || '').toString().trim();
      if (!id) return;
      var prev = S.done[id];
      var rec = {
        score: Number(r[c('Score')]) || 0,
        max: Number(r[c('Max Points')]) || 0,
        pending: Number(r[c('Awaiting Review')]) || 0,
        attempt: Number(r[c('Attempt')]) || 1,
        completed: (r[c('Completed')] || '').toString()
      };
      if (!prev || rec.attempt >= prev.attempt) S.done[id] = rec;
    });
  }

  /* ---------- list view ---------- */

  function weekLabel(w) {
    if (w === null || w === undefined || w === '') return 'Advanced and reference';
    return 'Week ' + w;
  }

  function progressBar(pct) {
    return '<div class="tr-bar"><div class="tr-bar-fill" style="width:' + pct + '%"></div></div>';
  }

  function renderList() {
    S.current = null;
    var mods = pathModules();
    if (!mods.length) {
      el('tr-root').innerHTML = '<div class="empty-state">No training path is assigned to this role yet.</div>';
      return;
    }

    var groups = {}, order = [];
    mods.forEach(function (m) {
      var k = (m.week === null || m.week === undefined) ? 'x' : String(m.week);
      if (!groups[k]) { groups[k] = []; order.push(k); }
      groups[k].push(m);
    });
    order.sort(function (a, b) {
      if (a === 'x') return 1;
      if (b === 'x') return -1;
      return Number(a) - Number(b);
    });

    var doneCount = mods.filter(function (m) { return S.done[m.id]; }).length;
    var pct = Math.round(doneCount / mods.length * 100);
    var pendingTotal = mods.reduce(function (a, m) {
      return a + (S.done[m.id] ? S.done[m.id].pending : 0);
    }, 0);

    var html = '<div class="tr-head">' +
      '<div class="tr-head-l"><div class="tr-head-num">' + doneCount + ' of ' + mods.length + '</div>' +
      '<div class="tr-head-lbl">modules complete</div></div>' +
      '<div class="tr-head-r">' + progressBar(pct) + '</div></div>';

    if (pendingTotal) {
      html += '<div class="alert alert-info" style="font-size:13px">' + pendingTotal +
        ' point' + (pendingTotal === 1 ? '' : 's') + ' worth of answers are with Rose and Justin for review.</div>';
    }

    order.forEach(function (k) {
      var list = groups[k];
      var dn = list.filter(function (m) { return S.done[m.id]; }).length;
      var mins = list.reduce(function (a, m) { return a + (Number(m.duration_min) || 0); }, 0);
      html += '<div class="tr-week">' +
        '<div class="tr-week-head"><span class="tr-week-name">' + esc(weekLabel(k === 'x' ? null : Number(k))) + '</span>' +
        '<span class="tr-week-meta">' + dn + ' of ' + list.length + ' complete, about ' + mins + ' min</span></div>';
      list.forEach(function (m) {
        var d = S.done[m.id];
        var pill = d
          ? (d.pending
            ? '<span class="pill pill-yellow">In review</span>'
            : '<span class="pill pill-approved">Complete</span>')
          : '<span class="pill pill-gray">Not started</span>';
        var score = d && d.max ? '<span class="tr-score">' + d.score + ' / ' + d.max + '</span>' : '';
        html += '<div class="tr-row" onclick="trOpen(\'' + esc(m.id) + '\')">' +
          '<div class="tr-row-l"><div class="tr-row-title">' + esc(m.title) + '</div>' +
          '<div class="tr-row-meta">' + esc(m.id) + ' &bull; ' + esc(m.track || '') +
          ' &bull; ' + (Number(m.duration_min) || 0) + ' min' +
          (m.has_quiz ? ' &bull; quiz' : '') + '</div></div>' +
          '<div class="tr-row-r">' + score + pill + '</div></div>';
      });
      html += '</div>';
    });

    el('tr-root').innerHTML = html;
  }

  /* ---------- module view ---------- */

  function questionHtml(q, qi) {
    var name = 'trq' + qi;
    var h = '<div class="tr-q" id="trq-wrap-' + qi + '">' +
      '<div class="tr-q-head"><span class="tr-q-n">' + (qi + 1) + '</span>' +
      '<span class="tr-q-text">' + inlineMd(q.q || '') + '</span>' +
      '<span class="tr-q-pts">' + (Number(q.points) || 0) + ' pts</span></div>';

    if (q.image) {
      h += '<div class="tr-q-img"><img src="' + esc(q.image) + '" alt=""></div>';
    }

    var t = q.type;
    if (t === 'image_options') {
      h += '<div class="tr-opts tr-opts-img">';
      (q.options || []).forEach(function (o, oi) {
        h += '<label class="tr-opt-img"><input type="radio" name="' + name + '" value="' + oi + '">' +
          '<img src="' + esc(o) + '" alt="Option ' + (oi + 1) + '"></label>';
      });
      h += '</div>';
    } else if (t === 'multi_select') {
      h += '<div class="tr-opts">';
      (q.options || []).forEach(function (o, oi) {
        h += '<label class="tr-opt"><input type="checkbox" name="' + name + '" value="' + oi + '"><span>' + esc(o) + '</span></label>';
      });
      h += '</div>';
    } else if (t === 'matching') {
      h += '<div class="tr-match">';
      (q.rows || []).forEach(function (r, ri) {
        h += '<div class="tr-match-row"><span class="tr-match-lbl">' + esc(r) + '</span>' +
          '<select class="form-input tr-match-sel" name="' + name + '" data-row="' + ri + '">' +
          '<option value="">Choose...</option>';
        (q.columns || []).forEach(function (cName, ci) {
          h += '<option value="' + ci + '">' + esc(cName) + '</option>';
        });
        h += '</select></div>';
      });
      h += '</div>';
    } else if (t === 'short_answer') {
      h += '<textarea class="form-textarea" id="' + name + '" rows="3" placeholder="Your answer..."></textarea>';
    } else if (t === 'file_upload') {
      h += '<input type="text" class="form-input" id="' + name + '" placeholder="Paste a OneDrive or Drive link to your screenshot...">';
    } else {
      h += '<div class="tr-opts">';
      (q.options || []).forEach(function (o, oi) {
        h += '<label class="tr-opt"><input type="radio" name="' + name + '" value="' + oi + '"><span>' + esc(o) + '</span></label>';
      });
      h += '</div>';
    }

    h += '<div class="tr-q-fb" id="trq-fb-' + qi + '"></div></div>';
    return h;
  }

  function renderModule(m) {
    S.current = m.id;
    var d = S.done[m.id];
    var total = quizTotal(m);

    var html = '<div class="tr-back"><a class="back-link" href="#" onclick="trBack();return false;">Back to all modules</a></div>' +
      '<div class="tr-mod-head"><div class="tr-mod-title">' + esc(m.title) + '</div>' +
      '<div class="tr-mod-meta">' + esc(m.id) + ' &bull; ' + esc(m.track || '') + ' &bull; ' +
      (Number(m.duration_min) || 0) + ' min' + (m.tier === 'advanced' ? ' &bull; advanced' : '') + '</div></div>';

    if (d) {
      html += '<div class="alert alert-success" style="font-size:13px">Submitted ' + esc(d.completed) +
        '. Score ' + d.score + ' of ' + d.max +
        (d.pending ? ', with ' + d.pending + ' points still in review.' : '.') +
        ' You can retake this quiz; the newest attempt is the one that counts.</div>';
    }

    html += videoBlock(m);
    html += '<div class="tr-body">' + md(m.body_md) + '</div>';

    if (m.has_quiz && (m.quiz || []).length) {
      html += '<div class="tr-quiz"><div class="card-title">Quiz</div>' +
        '<div class="tr-quiz-sub">' + m.quiz.length + ' questions, ' + total + ' points. ' +
        'Written answers and screenshots are reviewed by Rose and Justin.</div>';
      m.quiz.forEach(function (q, qi) { html += questionHtml(q, qi); });
      html += '<div id="tr-quiz-alert"></div>' +
        '<button class="submit-btn" id="tr-submit" onclick="trSubmit()">Submit Quiz</button></div>';
    } else {
      html += '<div id="tr-quiz-alert"></div>' +
        '<button class="submit-btn" id="tr-submit" onclick="trSubmit()">' +
        (d ? 'Mark Complete Again' : 'Mark Complete') + '</button>';
    }

    el('tr-root').innerHTML = html;
    window.scrollTo(0, 0);
  }

  /* ---------- grading ---------- */

  function readResponse(q, qi) {
    var name = 'trq' + qi;
    var t = q.type;
    if (t === 'multi_select') {
      var picked = [];
      Array.prototype.forEach.call(document.getElementsByName(name), function (n) {
        if (n.checked) picked.push(Number(n.value));
      });
      return { value: picked, text: picked.map(function (i) { return (q.options || [])[i]; }).join('; ') };
    }
    if (t === 'matching') {
      var sels = document.querySelectorAll('select[name="' + name + '"]');
      var vals = [], txt = [];
      Array.prototype.forEach.call(sels, function (s) {
        var v = s.value === '' ? null : Number(s.value);
        vals.push(v);
        txt.push((q.rows || [])[Number(s.getAttribute('data-row'))] + ' = ' +
          (v === null ? '(blank)' : (q.columns || [])[v]));
      });
      return { value: vals, text: txt.join('; ') };
    }
    if (t === 'short_answer' || t === 'file_upload') {
      var f = el(name);
      var v = f ? (f.value || '').trim() : '';
      return { value: v, text: v };
    }
    var chosen = null;
    Array.prototype.forEach.call(document.getElementsByName(name), function (n) {
      if (n.checked) chosen = Number(n.value);
    });
    var label = chosen === null ? '' : (q.options || [])[chosen];
    if (t === 'image_options' && chosen !== null) label = 'Option ' + (chosen + 1) + ' (' + label + ')';
    return { value: chosen, text: label || '' };
  }

  function gradeOne(q, resp) {
    var max = Number(q.points) || 0;
    if (!q.k) return { auto: false, score: 0, max: max, why: '' };
    var k = decKey(q.k);
    if (!k) return { auto: false, score: 0, max: max, why: '' };
    var ok = false;
    if (q.type === 'multi_select') ok = sameSet(resp.value, k.a || []);
    else if (q.type === 'matching') {
      var want = k.a || [];
      ok = Array.isArray(resp.value) && resp.value.length === want.length &&
        resp.value.every(function (v, i) { return v === want[i]; });
    } else ok = (resp.value !== null && resp.value === k.a);
    return { auto: true, correct: ok, score: ok ? max : 0, max: max, why: k.w || '' };
  }

  /* ---------- submit ---------- */

  async function submitModule(m) {
    if (S.busy) return;
    var alertEl = el('tr-quiz-alert');
    var btn = el('tr-submit');
    var qs = m.quiz || [];

    var results = [], unanswered = [];
    qs.forEach(function (q, qi) {
      var resp = readResponse(q, qi);
      var empty = (resp.value === null) ||
        (Array.isArray(resp.value) && (!resp.value.length || resp.value.indexOf(null) >= 0)) ||
        (typeof resp.value === 'string' && !resp.value);
      if (empty) unanswered.push(qi + 1);
      results.push({ q: q, qi: qi, resp: resp, grade: gradeOne(q, resp) });
    });

    if (unanswered.length) {
      if (alertEl) {
        alertEl.innerHTML = '<div class="alert alert-error">Answer every question before submitting. ' +
          'Missing: ' + unanswered.join(', ') + '.</div>';
      }
      return;
    }

    S.busy = true;
    if (btn) { btn.disabled = true; btn.textContent = 'Submitting...'; }

    var score = 0, autoMax = 0, pending = 0;
    results.forEach(function (r) {
      if (r.grade.auto) { score += r.grade.score; autoMax += r.grade.max; }
      else pending += r.grade.max;
    });
    var maxTotal = autoMax + pending;
    var attempt = (S.done[m.id] ? S.done[m.id].attempt : 0) + 1;

    try {
      // Read each header row once, not once per question.
      var dr = await api({ action: 'read', tab: TAB_RESP });
      if (!dr || !dr.success || !dr.data || !dr.data.length) throw new Error('responses header');
      var rc = cols(dr.data[0]);
      var rWidth = dr.data[0].length;

      // Per-question rows first, so a partial failure still leaves the answers.
      for (var i = 0; i < results.length; i++) {
        var r = results[i];
        var row = buildRow(rWidth, rc, [
          ['Employee', S.employee],
          ['Module ID', m.id],
          ['Module Title', m.title],
          ['Attempt', attempt],
          ['Question', r.q.q || ''],
          ['Type', r.q.type || ''],
          ['Response', r.resp.text],
          ['Auto Score', r.grade.auto ? r.grade.score : ''],
          ['Max Points', r.grade.max],
          ['Needs Review', r.grade.auto ? '' : 'Yes'],
          ['Submitted', todayStr()]
        ]);
        await api({ action: 'append', tab: TAB_RESP, row: JSON.stringify(row) });
      }

      var dd = await api({ action: 'read', tab: TAB_DONE });
      if (!dd || !dd.success || !dd.data || !dd.data.length) throw new Error('completions header');
      var dc = cols(dd.data[0]);
      var drow = buildRow(dd.data[0].length, dc, [
        ['Employee', S.employee],
        ['Module ID', m.id],
        ['Module Title', m.title],
        ['Week', m.week === null || m.week === undefined ? '' : m.week],
        ['Score', score],
        ['Max Points', maxTotal],
        ['Awaiting Review', pending],
        ['Attempt', attempt],
        ['Completed', todayStr()]
      ]);
      await api({ action: 'append', tab: TAB_DONE, row: JSON.stringify(drow) });

      if (pending) await emailReview(m, results, attempt);

      S.done[m.id] = {
        score: score, max: maxTotal, pending: pending,
        attempt: attempt, completed: todayStr()
      };

      showFeedback(results);
      if (alertEl) {
        alertEl.innerHTML = '<div class="alert alert-success">Submitted. ' + score + ' of ' + autoMax +
          ' on the auto-graded questions' +
          (pending ? ', plus ' + pending + ' points now with Rose and Justin for review.' : '.') + '</div>';
      }
      if (btn) { btn.textContent = 'Submitted'; }
    } catch (e) {
      console.error(e);
      if (alertEl) alertEl.innerHTML = '<div class="alert alert-error">Could not save your quiz. Please try again.</div>';
      if (btn) { btn.disabled = false; btn.textContent = 'Submit Quiz'; }
    }
    S.busy = false;
  }

  function showFeedback(results) {
    results.forEach(function (r) {
      var fb = el('trq-fb-' + r.qi);
      if (!fb) return;
      if (!r.grade.auto) {
        fb.innerHTML = '<span class="pill pill-yellow">Sent for review</span>';
        return;
      }
      var tag = r.grade.correct
        ? '<span class="pill pill-approved">Correct</span>'
        : '<span class="pill pill-denied">Not quite</span>';
      fb.innerHTML = tag + (r.grade.why ? '<div class="tr-why">' + inlineMd(r.grade.why.trim()) + '</div>' : '');
    });
  }

  async function emailReview(m, results, attempt) {
    var lines = results.filter(function (r) { return !r.grade.auto; }).map(function (r) {
      return '<p><strong>' + esc(r.q.q || '') + '</strong><br>' +
        '<em>' + esc(r.resp.text || '(blank)') + '</em><br>' +
        'Worth ' + r.grade.max + ' points.</p>';
    });
    var body = '<p>' + esc(S.employee) + ' submitted <strong>' + esc(m.title) +
      '</strong> (' + esc(m.id) + '), attempt ' + attempt + '.</p>' +
      '<p>' + lines.length + ' answer' + (lines.length === 1 ? '' : 's') + ' need review:</p>' +
      lines.join('') +
      '<p>Open the Training Progress tab in the portal to record a decision.</p>';
    try {
      await api({
        action: 'send_email',
        to_key: 'training',
        subject: 'Training review: ' + S.employee + ' - ' + m.title,
        body: body
      });
    } catch (e) { console.error('review email failed', e); }
  }

  /* ---------- window hooks ---------- */

  window.trOpen = function (id) {
    var m = S.modules.filter(function (x) { return x.id === id; })[0];
    if (m) renderModule(m);
  };

  window.trBack = function () { renderList(); };

  window.trSubmit = function () {
    if (!S.current) return;
    var m = S.modules.filter(function (x) { return x.id === S.current; })[0];
    if (m) submitModule(m);
  };

  /* ---------- styles ---------- */

  function injectStyles() {
    if (el('tr-style')) return;
    var css = [
      '.tr-head{display:flex;align-items:center;gap:20px;background:#fff;border:1px solid #e4dbd0;border-radius:8px;padding:16px 20px;margin-bottom:16px}',
      '.tr-head-num{font-family:"Barlow Condensed",Arial,sans-serif;font-size:26px;font-weight:700;color:#1a1a1a;line-height:1}',
      '.tr-head-lbl{font-size:12px;color:#aaa;text-transform:uppercase;letter-spacing:0.1em;margin-top:2px}',
      '.tr-head-r{flex:1}',
      '.tr-bar{background:#edeae4;border-radius:99px;height:8px;overflow:hidden}',
      '.tr-bar-fill{background:#c4581f;height:100%;border-radius:99px;transition:width .3s}',
      '.tr-week{margin-bottom:22px}',
      '.tr-week-head{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:8px}',
      '.tr-week-name{font-family:"Barlow Condensed",Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#1a1a1a}',
      '.tr-week-meta{font-size:12px;color:#aaa}',
      '.tr-row{display:flex;justify-content:space-between;align-items:center;gap:12px;background:#fff;border:1px solid #e4dbd0;border-radius:6px;padding:12px 14px;margin-bottom:6px;cursor:pointer;transition:border-color .15s}',
      '.tr-row:hover{border-color:#c4581f}',
      '.tr-row-title{font-weight:600;font-size:14px;color:#1a1a1a}',
      '.tr-row-meta{font-size:11px;color:#aaa;margin-top:2px}',
      '.tr-row-r{display:flex;align-items:center;gap:8px;white-space:nowrap}',
      '.tr-score{font-size:12px;color:#888;font-weight:600}',
      '.tr-back{margin-bottom:10px}',
      '.tr-mod-title{font-family:"Barlow Condensed",Arial,sans-serif;font-size:24px;font-weight:700;letter-spacing:0.04em;color:#1a1a1a}',
      '.tr-mod-meta{font-size:12px;color:#aaa;margin:2px 0 14px}',
      '.tr-video{position:relative;padding-bottom:56.25%;height:0;margin-bottom:18px;border-radius:8px;overflow:hidden;background:#1a1a1a}',
      '.tr-video iframe{position:absolute;top:0;left:0;width:100%;height:100%}',
      '.tr-body{background:#fff;border:1px solid #e4dbd0;border-radius:8px;padding:20px 22px;margin-bottom:18px}',
      '.tr-body .tr-h{font-family:"Barlow Condensed",Arial,sans-serif;letter-spacing:0.06em;text-transform:uppercase;color:#1a1a1a;margin:18px 0 8px}',
      '.tr-body h2.tr-h{font-size:19px}.tr-body h3.tr-h{font-size:16px}.tr-body h4.tr-h{font-size:14px}',
      '.tr-body .tr-h:first-child{margin-top:0}',
      '.tr-p{font-size:14px;line-height:1.65;color:#333;margin:0 0 12px}',
      '.tr-ul,.tr-ol{font-size:14px;line-height:1.65;color:#333;margin:0 0 12px;padding-left:22px}',
      '.tr-ul li,.tr-ol li{margin-bottom:5px}',
      '.tr-bq{border-left:3px solid #c4581f;background:#faf6f0;margin:0 0 12px;padding:10px 14px;font-size:14px;line-height:1.6;color:#555}',
      '.tr-code{background:#f0ece6;padding:1px 5px;border-radius:3px;font-size:13px}',
      '.tr-quiz{background:#fff;border:1px solid #e4dbd0;border-radius:8px;padding:20px 22px}',
      '.tr-quiz-sub{font-size:12px;color:#aaa;margin:-6px 0 16px}',
      '.tr-q{border-top:1px solid #edeae4;padding:16px 0}',
      '.tr-q:first-of-type{border-top:none;padding-top:0}',
      '.tr-q-head{display:flex;align-items:baseline;gap:8px;margin-bottom:10px}',
      '.tr-q-n{background:#1a1a1a;color:#fff;border-radius:99px;min-width:20px;height:20px;display:inline-flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;flex-shrink:0}',
      '.tr-q-text{flex:1;font-size:14px;font-weight:600;color:#1a1a1a;line-height:1.5}',
      '.tr-q-pts{font-size:11px;color:#aaa;white-space:nowrap}',
      '.tr-q-img{margin:0 0 12px}',
      '.tr-q-img img{max-width:100%;border:1px solid #e4dbd0;border-radius:6px}',
      '.tr-opts{display:flex;flex-direction:column;gap:6px}',
      '.tr-opt{display:flex;align-items:flex-start;gap:8px;font-size:14px;color:#333;cursor:pointer;padding:6px 8px;border-radius:5px}',
      '.tr-opt:hover{background:#faf6f0}',
      '.tr-opts-img{flex-direction:row;flex-wrap:wrap;gap:10px}',
      '.tr-opt-img{display:block;border:2px solid #e4dbd0;border-radius:6px;padding:6px;cursor:pointer;max-width:320px}',
      '.tr-opt-img:hover{border-color:#c4581f}',
      '.tr-opt-img img{max-width:100%;display:block;margin-top:6px}',
      '.tr-match-row{display:flex;align-items:center;gap:10px;margin-bottom:8px;flex-wrap:wrap}',
      '.tr-match-lbl{flex:1;min-width:180px;font-size:14px;color:#333}',
      '.tr-match-sel{width:180px}',
      '.tr-q-fb{margin-top:10px}',
      '.tr-why{font-size:13px;color:#666;line-height:1.55;margin-top:6px;padding-left:2px}'
    ].join('');
    var st = document.createElement('style');
    st.id = 'tr-style';
    st.textContent = css;
    document.head.appendChild(st);
  }

  /* ---------- init ---------- */

  window.initTraining = async function (employee, role) {
    S.employee = employee;
    S.role = role;
    injectStyles();
    var root = el('tr-root');
    if (!root) return;
    root.innerHTML = '<div class="loading">Loading training...</div>';
    try {
      await loadModules();
      await loadCompletions();
      renderList();
    } catch (e) {
      console.error(e);
      root.innerHTML = '<div class="alert alert-error">Could not load training content. Refresh to try again.</div>';
    }
  };
})();
